[versions]
# Lowest supported Bukkit version.
bukkit = "1.14.4-R0.1-SNAPSHOT"
# Corresponding Spigot version for optional Spigot-specific features.
spigot = "1.14.4-R0.1-SNAPSHOT"
# Corresponding CraftBukkit version. Only required for testing.
# Individual NMS modules can use other CraftBukkit versions.
craftbukkit = "1.14.4-R0.1-SNAPSHOT"

checkerframework = "3.21.2"

worldguard = "7.0.0"
towny = "0.98.1.0"
citizens = "2.0.29-SNAPSHOT"
vault = "1.7"
bstats = "1.5"

junit = "4.13.1"
hamcrest = "1.3"
asm = "9.1"

[libraries]
bukkit = { module = "org.bukkit:bukkit", version.ref = "bukkit" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
craftbukkit = { module = "org.bukkit:craftbukkit", version.ref = "craftbukkit" }

checkerframework-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
checkerframework-checker = { module = "org.checkerframework:checker", version.ref = "checkerframework" }

worldguard-bukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
#towny = { module = "com.github.TownyAdvanced:Towny", version.ref = "towny" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
citizens-main = { module = "net.citizensnpcs:citizens-main", version.ref = "citizens" }
vault-api = { module = "net.milkbowl.vault:VaultAPI", version.ref = "vault" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

junit = { module = "junit:junit", version.ref = "junit" }
hamcrest = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
