[versions]
# Minecraft
paper = "1.21-R0.1-SNAPSHOT"
minecraft = "1.21"

worldguard = "7.0.0"
towny = "0.98.1.0"
citizens = "2.0.30-SNAPSHOT"
vault = "1.7.1"
bstats = "1.5"

# Paper
paperweight = "1.7.1"
runPaper = "2.3.0"

# Other
shadowJar = "8.1.7"

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
shadowJar = { id = "io.github.goooler.shadow", version.ref = "shadowJar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }

worldguard-bukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
citizens-main = { module = "net.citizensnpcs:citizens-main", version.ref = "citizens" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }