[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Minecraft
paper = "1.21.3-R0.1-SNAPSHOT"
minecraft = "1.21.3"

# Gradle Plugins
paperweight = "1.7.5"
runPaper = "2.3.1"
minotaur = "2.8.7"
hangar = "0.1.2"
shadow = "8.3.0"

jdtannotations = "2.3.0"
nonpe = "1.0.3"
checkerframework = "3.46.0"

worldguard = "7.0.0"
towny = "0.98.1.0"
citizens = "2.0.30-SNAPSHOT"
vault = "1.7.1"
bstats = "1.5"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
jdt-annotations = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version.ref = "jdtannotations" }
nonpe-java21 = { module = "com.vegardit.no-npe:no-npe-eea-java-21", version.ref = "nonpe" }
checkerframework-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
checkerframework-checker = { module = "org.checkerframework:checker", version.ref = "checkerframework" }

worldguard-bukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
citizens-main = { module = "net.citizensnpcs:citizens-main", version.ref = "citizens" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }