# This name is also shown in the status badge.
name: Build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  # Rebuild periodically to keep the cache alive:
  schedule:
  - cron: '45 4 * * 0,3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # SonarCloud: Shallow clones should be disabled for a better relevancy of analysis
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-m2
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle
    - name: Cache Jabba JDK installations
      uses: actions/cache@v3
      with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-${{ hashFiles('**/*.sh') }}
        restore-keys: |
          ${{ runner.os }}-jabba
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
    - name: Build Shopkeepers
      run: ./build.sh
    - name: Run SonarCloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube
    # Upload workflow artifacts to allow the inspection of build results.
    # These are only retained for a few days.
    - name: Stage artifacts for upload
      run: mkdir staging && cp build/*.jar staging
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: staging
